In [1]:
# import the libraries
import numpy as np
import  pandas as pd
import  difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# Data Collection and preprocessing
movies_Data = pd.read_csv("/Users/tushark/Downloads/CSV/movies.csv")
movies_Data.head()


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [3]:
movies_Data.shape

(4803, 24)

In [4]:
movies_Data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [5]:
# selecting the relevant features for recommendation
select_feature = ['genres','homepage','keywords','overview']
print(select_feature)

['genres', 'homepage', 'keywords', 'overview']


In [6]:
# replacing the null values with null string
for feature in select_feature:
    movies_Data[feature]= movies_Data[feature].fillna('')

In [7]:
# combining all the 5 selected features
combine_feature = movies_Data['genres']+''+movies_Data['homepage']+''+movies_Data['keywords']+''+movies_Data['overview']
print(combine_feature)


0       Action Adventure Fantasy Science Fictionhttp:/...
1       Adventure Fantasy Actionhttp://disney.go.com/d...
2       Action Adventure Crimehttp://www.sonypictures....
3       Action Crime Drama Thrillerhttp://www.thedarkk...
4       Action Adventure Science Fictionhttp://movies....
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviehttp://www.hallma...
4801    http://shanghaicalling.com/When ambitious New ...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [8]:
# converting the text data to feature vectors
vectorizer = TfidfVectorizer()

In [13]:
feature_vectors = vectorizer.fit_transform(combine_feature)

In [14]:
print(feature_vectors)

  (0, 4767)	0.1993070355891856
  (0, 1181)	0.14639795514207554
  (0, 1376)	0.06525015234394367
  (0, 20688)	0.1993070355891856
  (0, 1404)	0.03766095473943227
  (0, 18919)	0.19040627452064032
  (0, 10786)	0.16944647209956581
  (0, 2858)	0.1202387883084142
  (0, 26962)	0.17910432383958555
  (0, 2641)	0.11483283562263422
  (0, 3791)	0.07371890975942942
  (0, 17296)	0.1307730245336401
  (0, 27773)	0.18126430088596054
  (0, 18801)	0.059287346946211954
  (0, 19268)	0.2195097473387857
  (0, 17494)	0.18891126210442888
  (0, 26874)	0.03704986400837945
  (0, 7699)	0.21561779435913622
  (0, 14342)	0.05239029218620321
  (0, 16532)	0.17020356277104023
  (0, 19322)	0.23582050610873628
  (0, 4342)	0.1485058386052287
  (0, 274)	0.22931668560362903
  (0, 26074)	0.06727451948090453
  (0, 24256)	0.2560232178583364
  :	:
  (4802, 27383)	0.09842569899491244
  (4802, 26281)	0.08576814863778792
  (4802, 18546)	0.07979894265699702
  (4802, 12138)	0.10196084475295518
  (4802, 28812)	0.09657191676094644
  (480

Cosine Similarity

In [15]:
# getting the similarity scores using cosine similarity
similarity  = cosine_similarity(feature_vectors)

In [16]:
print(similarity)

[[1.         0.04381929 0.03316354 ... 0.02796625 0.01955485 0.00831701]
 [0.04381929 1.         0.03715266 ... 0.04496986 0.03166346 0.01948293]
 [0.03316354 0.03715266 1.         ... 0.03675559 0.02120559 0.01569652]
 ...
 [0.02796625 0.04496986 0.03675559 ... 1.         0.05180998 0.02606262]
 [0.01955485 0.03166346 0.02120559 ... 0.05180998 1.         0.04334827]
 [0.00831701 0.01948293 0.01569652 ... 0.02606262 0.04334827 1.        ]]


Getting the Movie Name from User

In [17]:
# getting the movie name from user 
movies_name = input('Enter your Favourite movie name:')

In [18]:
# creating a list with all the movie names given in the dataset
list_of_all_title = movies_Data['original_title'].tolist()

In [19]:
print(list_of_all_title)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [20]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movies_name,list_of_all_title)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [21]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [22]:
# finding the index of the movie with title
index_of_the_movie = movies_Data[movies_Data.original_title == close_match]['index'].values[0]
print(index_of_the_movie)

68


In [23]:
# getting list of all similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.06067839056260051), (1, 0.03622170013021961), (2, 0.01650791758995127), (3, 0.014320096119933042), (4, 0.02389382981392913), (5, 0.03828077148297639), (6, 0.013852310328017712), (7, 0.15937098835977093), (8, 0.011485876163637939), (9, 0.03052208825047512), (10, 0.019885865548845395), (11, 0.014272107432694147), (12, 0.0070816718827075254), (13, 0.01234727304255741), (14, 0.048098294254823815), (15, 0.01987781168983981), (16, 0.14588235974137156), (17, 0.014383348213359936), (18, 0.02289922785732605), (19, 0.04052433395929934), (20, 0.04404548075998238), (21, 0.036741369602487264), (22, 0.00884946626891989), (23, 0.015228859239185632), (24, 0.006489502621003303), (25, 0.006752365067059088), (26, 0.09410696846493402), (27, 0.020024444212954268), (28, 0.031352969819953676), (29, 0.011033956594856396), (30, 0.07639084916484286), (31, 0.22367085177912255), (32, 0.03351800117902227), (33, 0.10469155940900127), (34, 0.0016489629293955403), (35, 0.06214803580744781), (36, 0.048367662553

In [24]:
len(similarity_score)

4803

In [25]:
# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score,key=lambda x:x[1],reverse=True) 
print(sorted_similar_movies)

[(68, 0.9999999999999999), (79, 0.2661602297285811), (31, 0.22367085177912255), (7, 0.15937098835977093), (4401, 0.1518597933543965), (16, 0.14588235974137156), (94, 0.12288611275381259), (182, 0.11386430210076877), (46, 0.10509476463508287), (33, 0.10469155940900127), (3606, 0.10155707134178939), (64, 0.0989589021695127), (1868, 0.09837370580937031), (553, 0.09679419042783563), (2229, 0.09487118733076948), (26, 0.09410696846493402), (511, 0.09372504532166817), (4033, 0.0934074715804122), (174, 0.09332101743373698), (101, 0.0912290163615853), (4325, 0.08901691599915378), (76, 0.0889444736328544), (1569, 0.08774551261716235), (85, 0.08380803645768516), (3414, 0.08341837651863367), (1135, 0.08335227414504706), (3133, 0.08224541902706016), (203, 0.08115106141380804), (783, 0.08029906597215074), (788, 0.07854249447503432), (1628, 0.07821863896161643), (394, 0.0773358571115509), (139, 0.07655158723758804), (30, 0.07639084916484286), (4648, 0.07583547511338262), (1177, 0.07495156038887234), 

In [26]:
# print the name of similar movies based on the index

print('Movies Suggested for You :\n')

i=1

for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_Data[movies_Data.index==index]['original_title'].values[0]
    if i<30:
        print(i,'_',title_from_index)
        i+=1

Movies Suggested for You :

1 _ Iron Man
2 _ Iron Man 2
3 _ Iron Man 3
4 _ Avengers: Age of Ultron
5 _ The Helix... Loaded
6 _ The Avengers
7 _ Guardians of the Galaxy
8 _ Ant-Man
9 _ X-Men: Days of Future Past
10 _ X-Men: The Last Stand
11 _ No Escape
12 _ X-Men: Apocalypse
13 _ Cradle 2 the Grave
14 _ The Kingdom
15 _ Machete Kills
16 _ Captain America: Civil War
17 _ X-Men
18 _ Super
19 _ The Incredible Hulk
20 _ X-Men: First Class
21 _ Beyond the Black Rainbow
22 _ G.I. Joe: The Rise of Cobra
23 _ Down to Earth
24 _ Captain America: The Winter Soldier
25 _ Incendies
26 _ Lord of War
27 _ The Devil's Tomb
28 _ X2
29 _ Mortdecai


Movie Recommendation System

In [28]:
movies_name = input('Enter Your Favourite Movie Name :\n')

list_of_all_title = movies_Data['original_title'].tolist()

find_close_match = difflib.get_close_matches(movies_name,list_of_all_title)

close_match  = find_close_match[0]

index_of_the_movie = movies_Data[movies_Data.original_title==close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score,key=lambda x:x[1],reverse=True)

print('Movies Suggested For you :\n')

i=1

for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_Data[movies_Data.index==index]['original_title'].values[0]
    if i<30:
        print(i,'_',title_from_index)
        i+=1
    
        

Movies Suggested For you :

1 _ Batman
2 _ Batman & Robin
3 _ The Dark Knight Rises
4 _ Batman Begins
5 _ The Dark Knight
6 _ Batman Forever
7 _ Batman Returns
8 _ Batman v Superman: Dawn of Justice
9 _ Suicide Squad
10 _ Batman: The Dark Knight Returns, Part 2
11 _ Spider-Man 2
12 _ Chill Factor
13 _ The Image Revolution
14 _ Dead Man Down
15 _ Superman
16 _ Superman II
17 _ A History of Violence
18 _ City By The Sea
19 _ Ballistic: Ecks vs. Sever
20 _ Wicked Blood
21 _ We Were Soldiers
22 _ Green Lantern
23 _ Sexy Beast
24 _ Superman III
25 _ Superman Returns
26 _ Underworld: Rise of the Lycans
27 _ Alex Cross
28 _ Free State of Jones
29 _ Man of Steel
