In [1]:
import numpy as np

matrix addtion

two matrix can be added only if they have same shape

In [5]:
# creating matrices

a = np.array([[2,3],[4,5]])
b =  np.array([[7,8],[8,9]])
print(a+b)



[[ 9 11]
 [12 14]]


In [7]:
print(a.shape)

(2, 2)


In [8]:
print(b.shape)

(2, 2)


crating matrix with random values

In [12]:
matrix = np.random.randint(20,size=(3,3))
matrix1 =np.random.randint(20,size=(3,3))
print(matrix)
print(matrix1)

[[ 8 18  4]
 [ 4 11 16]
 [ 7 14  9]]
[[18  9  1]
 [13 10  9]
 [11  4  9]]


In [14]:
sum = np.add(matrix,matrix1)
print(sum)

[[26 27  5]
 [17 21 25]
 [18 18 18]]


matrix substraction

In [15]:
matrix = np.random.randint(20,size=(3,3))
matrix1 =np.random.randint(20,size=(3,3))
print(matrix)
print(matrix1)

[[ 2  5 10]
 [15  2  7]
 [19 13  3]]
[[18 10 18]
 [15 14 11]
 [12 19 10]]


In [17]:
substraction = np.subtract(matrix,matrix1)
print(substraction)

[[-16  -5  -8]
 [  0 -12  -4]
 [  7  -6  -7]]


Multiplying a matrix by a scalar|

In [18]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[7 3 8 8]
 [0 1 5 0]
 [5 2 0 0]
 [2 6 7 1]]


In [20]:
product = np.multiply(x,y)


In [21]:
print(product)

[[35 15 40 40]
 [ 0  5 25  0]
 [25 10  0  0]
 [10 30 35  5]]


**Multiplying 2 Matrices**

In [22]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [23]:
print(matrix_3)

[[1 0 1]
 [1 2 0]
 [4 3 3]]


In [24]:
print(matrix_4)

[[3 0 4 3]
 [3 1 1 1]
 [0 2 4 0]]


In [25]:
product = np.dot(matrix_3, matrix_4)

In [26]:
print(product)

[[ 3  2  8  3]
 [ 9  2  6  5]
 [21  9 31 15]]


In [27]:
product.shape

(3, 4)

In [28]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [29]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

Element wise Matrix Multiplication

In [30]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [31]:
print(matrix_3)

[[3 3 0]
 [3 1 3]
 [2 1 1]]


In [32]:
print(matrix_4)

[[1 0 4]
 [4 2 4]
 [2 0 3]]


In [33]:
product = np.multiply(matrix_3, matrix_4)

In [34]:
print(product)

[[ 3  0  0]
 [12  2 12]
 [ 4  0  3]]


In [35]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [36]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 