In [1]:
import numpy as np

creting matrix using numpy


In [6]:
matrix1  = np.array([[2,3],[6,7]])
print(matrix1)



[[2 3]
 [6 7]]


In [7]:
matrix1.shape

(2, 2)

In [8]:
matrix2 = np.array([[10,23,45],[34,21,45],[5,56,8]])
print(matrix2)

[[10 23 45]
 [34 21 45]
 [ 5 56  8]]


creating matrix with random values

In [11]:
matrix3 = np.random.rand(2,3)
matrix3

array([[0.26278888, 0.03466104, 0.96948141],
       [0.79274388, 0.37066048, 0.19845602]])

In [13]:
# all values integer
matrix3 = np.random.randint(20 ,size=(4,5))
matrix3

array([[12, 18, 11, 10,  1],
       [ 2,  1,  7, 12,  9],
       [ 8,  1, 18,  0,  0],
       [11, 17, 16,  8,  2]])

matrix with all   one values

In [16]:
matrix4 = np.ones((2,3),dtype=int)
matrix4

array([[1, 1, 1],
       [1, 1, 1]])

matrix with  all values zeros

In [17]:
matrix5 = np.zeros((10,10),dtype= int)
matrix5

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

identity matrix

In [18]:
identity_matrix = np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Transpose of matrix

In [20]:
# matrix with random values
trans_matrix = np.random.randint(10,size=(3,3))
trans_matrix

array([[9, 4, 5],
       [2, 1, 6],
       [0, 3, 9]])

In [22]:
transpose_matrix =np.transpose(trans_matrix)
transpose_matrix

array([[9, 2, 0],
       [4, 1, 3],
       [5, 6, 9]])