
NumPy - Numerical Python

Advantages of Numpy Arrays:

Allows several Mathematical Operations
Faster operations

In [7]:
import  numpy as np # importing dependencies



list vs numpy time taken

In [8]:
from  time import process_time

time taken by  a list



In [9]:
python_list = [i for i in range(10000)]
star_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time-star_time) # for knowning the time


0.004550999999999972


In [10]:
np_array = np.array([i for i in range(10000)])
star_time =process_time()
np_array+=5
end_time=process_time()
print(end_time-star_time)

0.002737999999999907


#Numpy Array

In [12]:
#list 

list1  = np.array([1,2,3,4])
print(list1)
type(list1)

[1 2 3 4]


numpy.ndarray

In [14]:
# creating 1D array 
A = np.array([1,3,5,7,9])
print(A)

[1 3 5 7 9]


In [15]:
A.shape

(5,)

In [18]:
C = np.array([(1,3,5,7,9),(2,4,6,7,8)],dtype=float)
print(C)

[[1. 3. 5. 7. 9.]
 [2. 4. 6. 7. 8.]]


Initial placeholder in Numpy array

In [24]:
# creating numpy array of zeros
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# creating numpy array of ones
b = np.ones((4,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# array of particular value
c= np.full((3,2),2)
print(c)

[[2 2]
 [2 2]
 [2 2]]


In [29]:
# creating identity matrix
identity = np.eye(4,4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
# creating numpy array with random values
arr_rand = np.random.random((1,1))
print(arr_rand)

[[0.42603528]]


In [44]:
# random integer values array within specific range
E = np.random.randint(20,50,(2,3)) 
print(E)


[[46 46 22]
 [24 29 39]]


In [45]:
# array of evenly spaced values --> specifying the number of values required
D = np.random.randint(10,30,5)

In [48]:
print(D)

[28 16 29 15 17]


In [50]:
# array of evenly spaced values --> specifying the step
s = np.arange(10,50,5)
print(s)


[10 15 20 25 30 35 40 45]


In [51]:
# convert a list to numpy array
list2 = [1,2,3,4,5,7,6]

np_array= np.asanyarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5 7 6]


numpy.ndarray

# Analysing a numpy array

In [52]:
c = np.random.randint(10,90,(5,5))
print(c)


[[67 39 11 46 88]
 [34 18 25 10 23]
 [25 75 26 86 89]
 [67 61 65 87 37]
 [56 64 78 61 30]]


In [55]:
# array Dimension
print(c.shape)

(5, 5)


In [56]:
# number of dimension
print(c.ndim)

2


In [57]:
# number of elements in an array
print(c.size)


25


In [58]:
# checking the datatype of in an array
print(c.dtype)

int64


mathematical operation on a np array

In [60]:
list4 =[1,2,3,4,4]
list5 = [2,4,6,8,10]
 # concatenate or join two list
print(list4+list5)

[1, 2, 3, 4, 4, 2, 4, 6, 8, 10]


In [61]:
a1 =np.random.randint(10,20,(3,3))
b1 =np.random.randint(30,40,(3,3))

print(a1)
print(b1)

[[17 14 19]
 [13 13 19]
 [16 15 19]]
[[31 31 33]
 [36 37 37]
 [33 30 31]]


In [62]:
print(a1+b1)

[[48 45 52]
 [49 50 56]
 [49 45 50]]


In [63]:
print(a1-b1)
print(a1*b1)
print(a1/b1)

[[-14 -17 -14]
 [-23 -24 -18]
 [-17 -15 -12]]
[[527 434 627]
 [468 481 703]
 [528 450 589]]
[[0.5483871  0.4516129  0.57575758]
 [0.36111111 0.35135135 0.51351351]
 [0.48484848 0.5        0.61290323]]


In [65]:
print(np.add(a1,b1))

[[48 45 52]
 [49 50 56]
 [49 45 50]]


In [66]:
print(np.subtract(a1,b1))
print(np.multiply(a1,b1))
print(np.divide(a1,b1))

[[-14 -17 -14]
 [-23 -24 -18]
 [-17 -15 -12]]
[[527 434 627]
 [468 481 703]
 [528 450 589]]
[[0.5483871  0.4516129  0.57575758]
 [0.36111111 0.35135135 0.51351351]
 [0.48484848 0.5        0.61290323]]


Array Manipulation

In [67]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 7]
 [6 2 0]]
(2, 3)


In [70]:
# transpose of an array
trans =np.transpose(array)
print(trans)
print(trans.shape)

[[9 6]
 [9 2]
 [7 0]]
(3, 2)


In [71]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 9 6]
 [1 3 1]]
(2, 3)


In [72]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 1]
 [9 3]
 [6 1]]
(3, 2)


In [73]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 8 6]
 [7 9 7]]
(2, 3)


In [74]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 8]
 [6 7]
 [9 7]]
(3, 2)
